// Generates counter/src/meta.js (chapter order, choice labels, ending names) from stories/*-journey/.
// Run: node counter/gen-meta.js   (re-run after adding or renaming chapters/endings, then redeploy the worker)
const fs = require('fs'), path = require('path'), vm = require('vm');
const root = path.join(__dirname, '..', 'stories');
const out = {};
fs.readdirSync(root).filter(d => fs.statSync(path.join(root, d)).isDirectory()).forEach(d => {
  const dir = path.join(root, d), all = fs.readdirSync(dir).filter(f => f.endsWith('.js'));
  const files = ['journey.js', ...all.filter(f => /^(ch|n\d)/.test(f)).sort(), 'endings.js'];
  const ctx = { window: {} }; vm.createContext(ctx);
  files.forEach(f => vm.runInContext(fs.readFileSync(path.join(dir, f), 'utf8'), ctx, { filename: f }));
  Object.values(ctx.window.JOURNEYS).forEach(J => {
    const chapters = J.chapters.slice().sort((a, b) => a.n - b.n).map(c => ({
      id: c.id, n: c.n, code: c.code, title: c.title,
      choices: c.choices.map(ch => ({ id: ch.id, label: ch.label }))
    }));
    const endings = [];
    Object.keys(J.exits || {}).forEach(k => endings.push({ id: k, name: J.exits[k].name, exit: true }));
    (J.endings || []).forEach(e => endings.push({ id: e.id, name: e.name }));
    out[J.id] = { title: J.title, chapters, endings };
  });
});
const bad = [];
const re = /^[A-Za-z0-9_-]{1,40}$/;
Object.keys(out).forEach(j => {
  if (!re.test(j)) bad.push('journey ' + j);
  out[j].chapters.forEach(c => { if (!re.test(c.id)) bad.push('chapter ' + c.id); c.choices.forEach(ch => { if (!re.test(ch.id)) bad.push('choice ' + c.id + '.' + ch.id); }); });
  out[j].endings.forEach(e => { if (!re.test(e.id)) bad.push('ending ' + e.id); });
  const ids = out[j].endings.map(e => e.id); if (new Set(ids).size !== ids.length) bad.push('duplicate ending/exit id in ' + j);
});
if (bad.length) { console.error('ids that break the worker validation: ' + bad.join(', ')); process.exit(1); }
fs.writeFileSync(path.join(__dirname, 'src', 'meta.js'), '// GENERATED by counter/gen-meta.js. Do not edit by hand.\nexport const META = ' + JSON.stringify(out) + ';\n');
Object.keys(out).forEach(j => console.log(j, out[j].chapters.map(c => c.id + '(' + c.n + ')').join(','), '| endings', out[j].endings.length));
